ctrl_interface=/var/run/wpa_supplicant
ap_scan=0
fast_reauth=1

network={
    key_mgmt=IEEE8021X
    eap=TLS
    eapol_flags=0
    identity="supplicant.lab.local"
    ca_cert="/etc/certs/pnac-ca.pem"
    client_cert="/etc/certs/pnac-client.pem"

    private_key="pkcs11:model=tpm2;object=handle-0x81000005"
}