image: eve-wwan 
org: lfedge
config:
  binds:
    - /lib/modules:/lib/modules
    - /dev:/dev
    - /run:/run
    - /:/hostfs
    - /persist:/persist:rshared,rbind
  net: host
  capabilities:
    - all
  devices:
    - path: all
      type: a
