#!/bin/sh

# SPDX-License-Identifier: CC0-1.0
# 2024 Nitin Joshi <njoshi1@lenovo.com>
#
# Quecetel EM160R-GL FCC Lock Mechanism
#

date > /persist/unlock.date
if [ -f /persist/fcc-unlock-lenovo ]; then
  strace /opt/fcc_lenovo/DPR_Fcc_unlock_service 2>/persist/unlock.strace
  exit $?
fi

exit 0
