package utils

import (
	"crypto/sha1"
	"fmt"
	"math/rand"
	"net"
	"os"
	"strconv"
	"syscall"
	"time"
	"unsafe"

	"github.com/vishvananda/netlink"
	"golang.org/x/sys/unix"
)

// GenerateMAC returns a deterministic, locally administered, unicast MAC address
// derived from the device name and interface name.
//
// The MAC is generated by hashing stable identifiers to ensure that:
//   - the same device/interface pair always receives the same MAC,
//   - MAC addresses remain consistent across restarts,
//   - collisions are highly unlikely,
//   - the address does not conflict with real hardware.
//
// The locally administered bit is set and the multicast bit is cleared
// to guarantee the MAC is valid for use in virtualized environments.
func GenerateMAC(devName, ifaceName string) net.HardwareAddr {
	// Use a hash to get deterministic entropy
	h := sha1.Sum([]byte(devName + ":" + ifaceName))

	mac := make(net.HardwareAddr, 6)
	copy(mac, h[:6])

	// Set locally administered bit (bit 1 of first octet)
	mac[0] |= 0x02

	// Clear multicast bit (bit 0 of first octet)
	mac[0] &^= 0x01

	return mac
}

// FindUnusedPort picks a random unused TCP port on the given host IP by probing it.
func FindUnusedPort(hostIP net.IP) (uint16, error) {
	if hostIP == nil {
		return 0, fmt.Errorf("undefined host IP")
	}

	const (
		// default range for ephemeral ports (as defined by IANA)
		minPort   = 49152
		maxPort   = 65535
		maxTrials = 50
	)

	for i := 0; i < maxTrials; i++ {
		port := uint16(rand.Intn(maxPort-minPort+1) + minPort)
		addr := net.JoinHostPort(hostIP.String(), strconv.Itoa(int(port)))
		conn, err := net.DialTimeout("tcp", addr, time.Second)
		if err != nil {
			// If connection is refused or times out, assume port is unused.
			return port, nil
		}
		// Connection succeeded → port in use.
		_ = conn.Close()
	}

	return 0, fmt.Errorf("failed to find unused port on %s after %d attempts",
		hostIP, maxTrials)
}

// CreateTUN creates a new TUN (network tunnel) interface with the specified name.
// The interface is configured in TUN mode (no packet information header) and
// opened for read/write access via /dev/net/tun.
//
// The caller is responsible for configuring IP addresses, MTU, and routes,
// as well as closing the returned file descriptor when no longer needed.
//
// See: https://www.kernel.org/doc/Documentation/networking/tuntap.txt
func CreateTUN(name string) (*os.File, error) {
	fd, err := unix.Open("/dev/net/tun", unix.O_RDWR, 0)
	if err != nil {
		return nil, fmt.Errorf("failed to open /dev/net/tun: %w", err)
	}

	var ifr [unix.IFNAMSIZ + 64]byte
	flags := uint16(unix.IFF_TUN | unix.IFF_NO_PI)
	copy(ifr[:], name)
	*(*uint16)(unsafe.Pointer(&ifr[unix.IFNAMSIZ])) = flags

	if _, _, errno := syscall.Syscall(
		syscall.SYS_IOCTL,
		uintptr(fd),
		uintptr(syscall.TUNSETIFF),
		uintptr(unsafe.Pointer(&ifr[0])),
	); errno != 0 {
		unix.Close(fd)
		return nil, fmt.Errorf("ioctl TUNSETIFF failed: %v", errno)
	}

	f := os.NewFile(uintptr(fd), name)
	return f, nil
}

// CreateBridge creates a Linux bridge with the given name, brings it up,
// and assigns the specified IP addresses to it. IPs can be IPv4 or IPv6.
func CreateBridge(name string, addrs []*net.IPNet, groupFwdMask uint16) error {
	br := &netlink.Bridge{
		LinkAttrs: netlink.LinkAttrs{
			Name: name,
		},
	}
	if groupFwdMask != 0 {
		br.GroupFwdMask = &groupFwdMask
	}
	if err := netlink.LinkAdd(br); err != nil {
		return fmt.Errorf("failed to add bridge %q: %w", name, err)
	}
	if err := netlink.LinkSetUp(br); err != nil {
		return fmt.Errorf("failed to set bridge %q UP: %w", name, err)
	}
	for _, ipnet := range addrs {
		addr := &netlink.Addr{IPNet: ipnet}
		if err := netlink.AddrAdd(br, addr); err != nil {
			return fmt.Errorf("failed to assign IP %s to bridge %q: %w",
				ipnet.String(), name, err)
		}
	}
	return nil
}

// DeleteBridge brings a bridge DOWN and deletes it.
func DeleteBridge(name string) error {
	link, err := netlink.LinkByName(name)
	if err != nil {
		return fmt.Errorf("failed to get link for bridge %q: %w", name, err)
	}
	if err = netlink.LinkSetDown(link); err != nil {
		return fmt.Errorf("failed to set bridge %q DOWN: %w", name, err)
	}
	if err = netlink.LinkDel(link); err != nil {
		return fmt.Errorf("failed to delete bridge %q: %w", name, err)
	}
	return nil
}

// CreateTap creates a TAP interface and brings it UP.
func CreateTap(name string) error {
	tap := &netlink.Tuntap{
		LinkAttrs: netlink.LinkAttrs{
			Name: name,
		},
		Mode: netlink.TUNTAP_MODE_TAP,
	}
	if err := netlink.LinkAdd(tap); err != nil {
		return fmt.Errorf("failed to create TAP %q: %w", name, err)
	}
	if err := netlink.LinkSetUp(tap); err != nil {
		return fmt.Errorf("failed to set TAP %q UP: %w", name, err)
	}
	return nil
}

// DeleteTap deletes a TAP interface.
func DeleteTap(name string) error {
	link, err := netlink.LinkByName(name)
	if err != nil {
		return fmt.Errorf("failed to get link for TAP %q: %w", name, err)
	}
	if err = netlink.LinkSetDown(link); err != nil {
		return fmt.Errorf("failed to set TAP %q DOWN: %w", name, err)
	}
	if err = netlink.LinkDel(link); err != nil {
		return fmt.Errorf("failed to delete TAP %q: %w", name, err)
	}
	return nil
}

// ConnectTapToBridge attaches a TAP interface to a Linux bridge by setting
// the bridge as the TAP interface's master.
func ConnectTapToBridge(bridgeName, tapName string) error {
	br, err := netlink.LinkByName(bridgeName)
	if err != nil {
		return fmt.Errorf("bridge %q not found: %w", bridgeName, err)
	}
	tap, err := netlink.LinkByName(tapName)
	if err != nil {
		return fmt.Errorf("TAP %q not found: %w", tapName, err)
	}
	if err = netlink.LinkSetMaster(tap, br); err != nil {
		return fmt.Errorf("failed to attach TAP %q to bridge %q: %w",
			tapName, bridgeName, err)
	}
	return nil
}

// CreateDummyInterface creates a dummy interface with the given name and assigns
// the provided IP addresses.
// Each IP should include the CIDR mask (/32 for IPv4, /128 for IPv6).
func CreateDummyInterface(name string, ips []net.IPNet) error {
	dummy := &netlink.Dummy{
		LinkAttrs: netlink.LinkAttrs{
			Name: name,
		},
	}
	if err := netlink.LinkAdd(dummy); err != nil {
		return fmt.Errorf("failed to create dummy %q: %w", name, err)
	}
	if err := netlink.LinkSetUp(dummy); err != nil {
		return fmt.Errorf("failed to bring up dummy %q: %w", name, err)
	}
	for _, ip := range ips {
		addr := &netlink.Addr{IPNet: &ip}
		err := netlink.AddrAdd(dummy, addr)
		if err != nil && !os.IsExist(err) {
			return fmt.Errorf("failed to add IP %s to dummy %q: %w",
				ip.String(), name, err)
		}
	}
	return nil
}
