---
name: Eden
on:
  pull_request:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"

jobs:
  integration:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        hv: ["kvm", "zfs-kvm"]
    steps:
      - name: Check
        run: |
          for addr in $(ip addr list|sed -En -e 's/.*inet ([0-9.]+).*/\1/p')
          do
              if echo "$addr" | grep -q -E "10.11.(12|13).[0-9]+"; then
                echo "$addr overlaps with test"; exit 1
              fi
          done
      - name: setup
        run: |
          sudo add-apt-repository ppa:canonical-server/server-backports
          sudo apt install -y qemu-utils qemu-system-x86 jq
      - name: get eve
        uses: actions/checkout@v2
        with:
          path: 'eve'
      - name: prepare eden
        run: |
          if [ -f ${{ github.workspace }}/eve/tests/eden/eden-version ]; then
            EDEN_VERSION=$(cat ${{ github.workspace }}/eve/tests/eden/eden-version)
          else
            EDEN_VERSION=lfedge/eden:0.4.0
          fi
          docker run -v $PWD:/out $EDEN_VERSION cp -a /eden/. /out/
          sudo chown -R $(whoami) .
          ./eden config add default
      - name: fetch or build eve
        env:
          TAG: pr${{ github.event.pull_request.number }}
          CACHE: evebuild/danger
        run: |
          if docker pull "$CACHE:$TAG-${{ matrix.hv }}"; then
             docker tag  "$CACHE:$TAG-${{ matrix.hv }}" "lfedge/eve:$TAG-${{ matrix.hv }}"
             docker tag  "$CACHE:$TAG-${{ matrix.hv }}" "lfedge/eve:$TAG-${{ matrix.hv }}-amd64"
          else
             make -C eve V=1 pkgs
             make -C eve V=1 ROOTFS_VERSION="$TAG" HV=${{ matrix.hv }} eve
             IMAGES="$(docker images -f reference="lfedge/eve-*" -q)"
             IMAGES="$IMAGES $(docker images -f reference="eve-build-*" -q)"
             IMAGES="$IMAGES $(docker images -f reference="golang" -q)"
             IMAGES="$IMAGES $(docker images -f dangling=true -q)"
             docker rmi -f $IMAGES||echo "skip conflicts"
             rm -rf ~/.linuxkit
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: set debug log level
        if: contains(github.event.review.body, '#eden-debug')
        run: |
          ./eden config set default --key=eve.log-level --value=debug
          ./eden config set default --key=eve.adam-log-level --value=debug
      - name: run
        run: |
          ./eden config set default --key eve.tag --value="$TAG"
          ./eden config set default --key eve.hv --value="${{ matrix.hv }}"
          ./eden config set default --key=eve.accel --value=false
          ./eden config set default --key=eve.cpu --value=2
          ./eden config set default --key=eden.tests --value=${{ github.workspace }}/eve/tests/eden
          EDITOR=cat ./eden config edit default
          echo > ${{ github.workspace }}/eve/tests/eden/workflow/testdata/eden_stop.txt
          ./eden test ${{ github.workspace }}/eve/tests/eden/workflow -v debug
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 45
      - name: Collect logs
        if: ${{ always() }}
        run: |
          ./eden log --format json > trace.log || echo "no log"
          ./eden info > info.log || echo "no info"
          ./eden metric > metric.log || echo "no metric"
          ./eden netstat > netstat.log || echo "no netstat"
          cp dist/default-eve.log console.log || echo "no device log"
          docker logs eden_adam > adam.log 2>&1 || echo "no adam log"
      - name: Log counting
        if: ${{ always() }}
        run: |
          echo "::group::Total errors"
          echo "$(jq '.severity' trace.log|grep err|wc -l)"
          echo "::endgroup::"
          echo "::group::Errors by source"
          echo "errors by source: $(jq -s 'map(select(.severity|contains("err")))|group_by(.source)|map({"source": .[0].source, "total":length})|sort_by(.total)|reverse[]' trace.log)"
          echo "::endgroup::"
          echo "::group::Error log content duplicates"
          echo "$(jq -s 'map(select(.severity | contains("err")))|group_by(.content)|map(select(length>1))' trace.log)"
          echo "::endgroup::"
          echo "::group::Error log function filename duplicates"
          echo "$(jq -s 'map(select(.severity | contains("err")))|group_by(.filename)|map(select(length>10))|map({"source": .[0].source, "filename": .[0].filename, "function": .[0].function, "content": [.[].content], "total":length})|sort_by(.total)| reverse[]' trace.log)"
          echo "::endgroup::"
          echo "::group::Segfaults"
          echo "$(jq -s 'map(select(.content | contains("segfault at")))' trace.log)"|tee segfaults.log
          [ "$(jq length segfaults.log)" -gt 0 ] && echo "::warning::segfaults found, you can see them in Log counting->Segfaults section"
          echo "::endgroup::"
      - name: Store raw test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: eden-report-${{ matrix.hv }}
          path: |
            ${{ github.workspace }}/trace.log
            ${{ github.workspace }}/info.log
            ${{ github.workspace }}/metric.log
            ${{ github.workspace }}/netstat.log
            ${{ github.workspace }}/console.log
            ${{ github.workspace }}/adam.log
