---
name: Unit tests
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-stable"
  pull_request:
    branches:
      - "master"
      - "[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+-stable"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Test
        run: |
          make test
      - name : Test (TPM Required)
        timeout-minutes: 30
        run: |
          bash tools/tpm-tests-on-qemu.sh
      - name: Report test results as Annotations
        if: ${{ always() }}
        uses: guyarb/golang-test-annoations@v0.6.0
        with:
          test-results: dist/amd64/results.json
      - name: Store raw test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: 'test-report'
          path: ${{ github.workspace }}/dist
      - name: Get code coverage
        uses: codecov/codecov-action@v3
